### ISSUE TITLE
Error executing action 'update' on resource 'chef_client_updater[update_chef-client]'

### ISSUE THREAD

**Issue by anniehedgpeth** [chef-cookbooks/chef_client_updater#106]
### Cookbook version
3.2.9

### Chef-client version
12.8.1

### Platform Details
Windows Server 2012 R2 Datacenter

### Scenario:
Trying to upgrade to Chef 14 by putting the chef_client_updater recipe or resource at the beginning of my run-list

### Steps to Reproduce:
I first tried to use just the `chef_client_updater` resource and then tried to just include the recipe, and both gave the same error. I also tried to manually run `chef_upgrade.ps1`, and it didn't run even though it's a valid file.

### Expected Result:
I'm expecting for this resource/recipe to converge and update Chef client on the node.

### Actual Result:
```
Error executing action 'update' on resource 'chef_client_updater[update_chef-client]'
```
```
#<NoMethodError: chef_client_updater[update chef-client] (chef_client_updater::default line 25) had an error: NoMethodError: undefined method `[]' for nil:NilClass> had an error:
chef_client_updater[update chef-client] (chef_client_updater::default line 25) had an error: NoMethodError: undefined method `[]' for nil:NilClass
```
### Description: 
```
Error executing action `update` on resource 'chef_client_updater[update chef-client]'
```
### NoMethodError
```
undefined method `[]' for nil:NilClass
```
### Cookbook Trace:
```
c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:351:in `rescue in block in class_from_file'
c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:330:in `block in class_from_file'
c:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
c:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
c:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
c:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
c:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
```
### Resource Declaration:
```
# In c:/chef/cache/cookbooks/chef_client_updater/recipes/default.rb

 25: chef_client_updater 'update chef-client' do
 26:   channel node['chef_client_updater']['channel']
 27:   version node['chef_client_updater']['version']
 28:   prevent_downgrade node['chef_client_updater']['prevent_downgrade']
 29:   post_install_action node['chef_client_updater']['post_install_action']
 30:   download_url_override node['chef_client_updater']['download_url_override'] if node['chef_client_updater']['download_url_override']
 31:   checksum node['chef_client_updater']['checksum'] if node['chef_client_updater']['checksum']
 32:   upgrade_delay node['chef_client_updater']['upgrade_delay'] unless node['chef_client_updater']['upgrade_delay'].nil?
 33:   product_name node['chef_client_updater']['product_name'] if node['chef_client_updater']['product_name']
 34: end
```
### Compiled Resource:
```
# Declared in c:/chef/cache/cookbooks/chef_client_updater/recipes/default.rb:25:in `from_file'

chef_client_updater("update chef-client") do
  action [:update]
  updated true
  updated_by_last_action true
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :chef_client_updater
  cookbook_name "chef_client_updater"
  recipe_name "default"
  channel "stable"
  version "14.0.190"
  prevent_downgrade true
  post_install_action "kill"
  product_name "chef"
end
```
## Stacktrace
```
c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:351:in `rescue in block in class_from_file'
c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:330:in `block in class_from_file'
(eval):2:in `block in action_update'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider.rb:360:in `instance_eval'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider.rb:360:in `compile_and_converge_action'
(eval):2:in `action_update'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider.rb:144:in `run_action'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource.rb:596:in `run_action'
c:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
c:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
c:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
c:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/resource_list.rb:84:in `block in execute_each_resource'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/resource_list.rb:82:in `execute_each_resource'
c:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/client.rb:668:in `block in converge'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/client.rb:663:in `catch'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/client.rb:663:in `converge'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/client.rb:702:in `converge_and_save'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/client.rb:280:in `run'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application.rb:252:in `run_with_graceful_exit_option'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application.rb:228:in `block in run_chef_client'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application.rb:211:in `run_chef_client'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application/client.rb:417:in `run_application'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application.rb:58:in `run'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/bin/chef-client:26:in `<top (required)>'
c:/opscode/push-jobs-client/bin/chef-client:63:in `load'
c:/opscode/push-jobs-client/bin/chef-client:63:in `<main>'
```

**Comment by lamont-granquist** [comment]
the compat_resource cookbook might be problematic.  should make sure you're at least on the latest version of that.  ideally you'd want to not use that, but since you're on 12.8.1 there's a bit of a chicken-and-egg there.

**Comment by lamont-granquist** [comment]
oh

https://github.com/chef-cookbooks/chef_client_updater/blob/v3.2.9/providers/default.rb#L351

`node['chef_client']['init_style'] == 'init'` is throwing because `node['chef_client']` doesn't exist.
