### ISSUE TITLE
Error executing action 'update' on resource 'chef_client_updater[Install 14.0.190 and kill]'

### ISSUE THREAD

**Issue by anniehedgpeth** [chef-cookbooks/chef_client_updater#108]
### Cookbook version
3.3.0

### Chef-client version
12.8.1

### Platform Details
Windows Server 2012 R2 Datacenter - Azure

### Scenario:
Trying to upgrade to Chef 14 by putting the chef_client_updater resource in a cookbook at the beginning of my run-list

### Steps to Reproduce:
Before you fixed the last bug, I was including the `chef_client_updater` recipe, but after the bug fix with 3.3.0, I went back to using just the resource and tried again to run it to no avail. I also tried to manually run chef_upgrade.ps1, and it didn't run.

### Expected Result:
I'm expecting chef_client_updater resource to execute.

## Actual Result:
`Error executing action 'update' on resource 'chef_client_updater[Install 14.0.190 and kill]'`
### #<SystemExit: chef_client_updater[Install 14.0.190 and kill] (relone_operations::setup line 7) had an error: SystemExit: exit> had an error:
```
chef_client_updater[Install 14.0.190 and kill] (relone_operations::setup line 7) had an error: SystemExit: exit
```
#### SystemExit
```
exit
```
### Cookbook Trace:
```
c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:180:in `exit'
c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:180:in `run_post_install_action'
c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:348:in `block (2 levels) in class_from_file'
c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:347:in `block in class_from_file'
c:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
c:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
c:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
c:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
c:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
```
### Resource Declaration:
```
# In c:/chef/cache/cookbooks/relone_operations/recipes/setup.rb

  7: chef_client_updater "Install #{desired_chef_version} and kill" do
  8:   version desired_chef_version
  9:   prevent_downgrade node['chef_client_updater']['prevent_downgrade']
 10: end
 11: 
```
### Compiled Resource:
```
# Declared in c:/chef/cache/cookbooks/relone_operations/recipes/setup.rb:7:in `from_file'

chef_client_updater("Install 14.0.190 and kill") do
  action [:update]
  updated true
  updated_by_last_action true
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :chef_client_updater
  cookbook_name "relone_operations"
  recipe_name "setup"
  version "14.0.190"
  prevent_downgrade true
  product_name "chef"
  post_install_action "kill"
end
```
### Stacktrace
```
c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:180:in `exit'
c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:180:in `run_post_install_action'
c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:348:in `block (2 levels) in class_from_file'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/mixin/why_run.rb:52:in `add_action'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider.rb:175:in `converge_by'
c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:347:in `block in class_from_file'
(eval):2:in `block in action_update'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider.rb:360:in `instance_eval'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider.rb:360:in `compile_and_converge_action'
(eval):2:in `action_update'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider.rb:144:in `run_action'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource.rb:596:in `run_action'
c:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
c:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
c:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
c:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/resource_list.rb:84:in `block in execute_each_resource'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/resource_list.rb:82:in `execute_each_resource'
c:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/client.rb:668:in `block in converge'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/client.rb:663:in `catch'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/client.rb:663:in `converge'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/client.rb:702:in `converge_and_save'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/client.rb:280:in `run'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application.rb:252:in `run_with_graceful_exit_option'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application.rb:228:in `block in run_chef_client'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application.rb:211:in `run_chef_client'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application/client.rb:417:in `run_application'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application.rb:58:in `run'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/bin/chef-client:26:in `<top (required)>'
c:/opscode/push-jobs-client/bin/chef-client:63:in `load'
c:/opscode/push-jobs-client/bin/chef-client:63:in `<main>'
```

**Comment by lamont-granquist** [comment]
Believe that means it worked fine.

https://github.com/chef-cookbooks/chef_client_updater/blob/master/providers/default.rb#L180

That's the normal exit line.  In chef-12 it certainly didn't know anything about it and couldn't handle that so it just blows up, but that's normal.

**Comment by anniehedgpeth** [comment]
I got on the node and stepped through `:/opscode/chef_upgrade.ps1`, and it exited on line 6 because a ruby.exe process was running - push jobs. Therefor, I believe this code won't work if you're running push jobs.

**Comment by algaut** [comment]
I had the same problem while trying to update from chef-client v13.4 to 13.8, nothing was happening after the client exited.
Updating c:/opscode/chef_upgrade.ps1 to stop push-jobs-client seems to do the trick

**Comment by tas50** [comment]
This fix has been released. Thanks @anniehedgpeth
