### ISSUE TITLE
Error on Windows - Exit during update phase

### ISSUE THREAD

**Issue by Makayez** [chef-cookbooks/chef_client_updater#112]
### Cookbook version
3.3.2

### Chef-client version
12.9.41

### Platform Details
Microsoft Windows [Version 6.3.9600] 

### Scenario:
On run, errors on step for exiting - removes c:\opscode\chef\* but never continues with install.

```[2018-04-12T14:21:53-07:00] WARN: Ohai::Config[:disabled_plugins] is set. Ohai::Config[:disabled_plugins] is deprecated and will be removed in future releases of ohai. Use ohai.disabled_plugins in your configuration f
ile to configure :disabled_plugins for ohai.
[2018-04-12T14:22:06-07:00] WARN: Run List override has been provided.
[2018-04-12T14:22:06-07:00] WARN: Original Run List: [role[qa_app-all], recipe[chef_client_updater]]
[2018-04-12T14:22:06-07:00] WARN: Overridden Run List: [recipe[chef_client_updater::default]]
[2018-04-12T14:22:06-07:00] INFO: Run List is [recipe[chef_client_updater::default]]
[2018-04-12T14:22:06-07:00] INFO: Run List expands to [chef_client_updater::default]
[2018-04-12T14:22:06-07:00] INFO: Starting Chef Run for W8-HOST
[2018-04-12T14:22:06-07:00] INFO: Running start handlers
[2018-04-12T14:22:06-07:00] INFO: Start handlers complete.
resolving cookbooks for run list: ["chef_client_updater::default"]
[2018-04-12T14:22:06-07:00] INFO: Loading cookbooks [chef_client_updater@3.3.2]
[2018-04-12T14:22:06-07:00] INFO: Skipping removal of obsoleted cookbooks from the cache
Synchronizing Cookbooks:
  - chef_client_updater (3.3.2)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 1 resources
Recipe: chef_client_updater::default
  * chef_client_updater[update-chef-client] action update[2018-04-12T14:22:07-07:00] INFO: Processing chef_client_updater[update-chef-client] action update (chef_client_updater::default line 36)

    * powershell_script[name] action run[2018-04-12T14:22:28-07:00] INFO: Processing powershell_script[name] action run (C:/chef/cache/cookbooks/chef_client_updater/providers/default.rb line 296)
SUCCESS: The scheduled task "Chef_upgrade" has successfully been created.
[2018-04-12T14:22:29-07:00] INFO: powershell_script[name] ran successfully

    - execute "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/F-TDSC~1/AppData/Local/Temp/chef-script20180412-7156-1kmfy56.ps1"
    - upgrade chef-client 12.9.41 to 13.8.11[2018-04-12T14:22:29-07:00] WARN: post_install_action "exec" not supported for chef-client running forked -- changing to "kill".
[2018-04-12T14:22:29-07:00] WARN: forcing "exec" to "kill" on windows.
[2018-04-12T14:22:29-07:00] WARN: New chef-client installed and exit is allowed. Forcing chef exit!
←[0m
    ================================================================================
    Error executing action `update` on resource 'chef_client_updater[update-chef-client]'
    ================================================================================

    SystemExit
    ----------
    exit

    Resource Declaration:
    ---------------------
    # In C:/chef/cache/cookbooks/chef_client_updater/recipes/default.rb

     36: chef_client_updater 'update-chef-client' do
     37:   version '13.8.11'
     38:   download_url_override 'https://artifact/repo/chef-windows-client-x64/13.8.11/chef-windows-client-x64-13.8.11-x64.msi'
     39:   checksum '25c703511cd3ab38604ca07938ad238b381c4f30d4375f87f67ecd04bcbb4f90'
     40:   post_install_action 'exec'
     41: end

    Compiled Resource:
    ------------------
    # Declared in C:/chef/cache/cookbooks/chef_client_updater/recipes/default.rb:36:in `from_file'

    chef_client_updater("update-chef-client") do
      action [:update]
      updated true
      updated_by_last_action true
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :chef_client_updater
      cookbook_name "chef_client_updater"
      recipe_name "default"
      version "13.8.11"
      download_url_override "https://artifact/repo/chef-windows-client-x64/13.8.11/chef-windows-client-x64-13.8.11-x64.msi"
      checksum "25c703511cd3ab38604ca07938ad238b381c4f30d4375f87f67ecd04bcbb4f90"
      post_install_action "kill"
      product_name "chef"
      exec_command "C:/opscode/chef/bin/chef-client"
    end

    Platform:
    ---------
    x64-mingw32

[2018-04-12T14:22:30-07:00] INFO: Running queued delayed notifications before re-raising exception
←[0m
Running handlers:
[2018-04-12T14:22:30-07:00] ERROR: Running exception handlers
Running handlers complete
[2018-04-12T14:22:30-07:00] ERROR: Exception handlers complete
Chef Client failed. 1 resources updated in 36 seconds
[2018-04-12T14:22:30-07:00] INFO: Sending resource update report (run-id: df7383fd-072d-43d2-a0eb-70ad930c50c9)
[2018-04-12T14:22:30-07:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
[2018-04-12T14:22:30-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
The batch file cannot be found.

C:\opscode>dir
 Volume in drive C has no label.
 Volume Serial Number is EE58-419E

 Directory of C:\opscode

04/12/2018  02:22 PM    <DIR>          .
04/12/2018  02:22 PM    <DIR>          ..
04/12/2018  01:39 PM    <DIR>          chef
04/12/2018  02:22 PM    <DIR>          chef.upgrade
04/12/2018  02:22 PM            16,876 chef_upgrade.ps1
               1 File(s)         16,876 bytes
               4 Dir(s)  90,749,988,864 bytes free
```

### Steps to Reproduce:
Run cookbook on Windows 8 client with override url (holding omnibus package for Chef 13.8.11)

### Expected Result:
Clean exit, Scheduled job should then perform clean-up.

### Actual Result:
Errors on exit, cleanup doesn't occur completely (chef gets erased, but installation seems broken - chef doesn't run)

**Comment by gsreynolds** [comment]
Hi @Makayez, this may be related to #110 where the contents of `C:\opscode\chef` are not fully removed and so the upgrade script fails. 

* Can you check the contents of `C:\opscode\chef`? `chef-log.dll` may the only file that was unable to be removed in a path like `C:\opscode\chef\embedded\lib\ruby\gems\2.3.0\gems\chef-12.9.41-universal-mingw32\ext\win32-eventlog\chef-log.dll`
* Can you try running the `chef_upgrade.ps1` script manually and see if/where it fails?

**Comment by Makayez** [comment]
I looked at #110 and disabled AV on the system to take that out of the potential issue.
On a re-run of the cookbook, I received the same error.

To answer your questions:
Immediately after failing, if I look - C:\opscode\chef still has a full installation:
```
C:\opscode>dir chef                                                                                                                                                                                                                         
 Volume in drive C has no label.                                                                                                                                                                                                            
 Volume Serial Number is EE58-419E                                                                                                                                                                                                          
                                                                                                                                                                                                                                            
 Directory of C:\opscode\chef                                                                                                                                                                                                               
                                                                                                                                                                                                                                            
04/13/2018  01:38 PM    <DIR>          .                                                                                                                                                                                                    
04/13/2018  01:38 PM    <DIR>          ..                                                                                                                                                                                                   
04/13/2018  01:42 PM    <DIR>          bin                                                                                                                                                                                                  
04/13/2018  01:38 PM    <DIR>          embedded                                                                                                                                                                                             
04/13/2018  01:38 PM            14,776 LICENSE                                                                                                                                                                                              
04/13/2018  01:38 PM    <DIR>          LICENSES                                                                                                                                                                                             
04/13/2018  01:38 PM    <DIR>          modules                                                                                                                                                                                              
04/13/2018  01:38 PM             8,174 version-manifest.json                                                                                                                                                                                
04/13/2018  01:38 PM             4,176 version-manifest.txt                                                                                                                                                                                 
               3 File(s)         27,126 bytes
```

Waiting 1 minute, the C:\opscode\chef is completely empty:
```
C:\opscode\chef>dir                                                                                                                                                                                                                         
 Volume in drive C has no label.                                                                                                                                                                                                            
 Volume Serial Number is EE58-419E                                                                                                                                                                                                          
                                                                                                                                                                                                                                            
 Directory of C:\opscode\chef                                                                                                                                                                                                               
                                                                                                                                                                                                                                            
04/13/2018  01:43 PM    <DIR>          .                                                                                                                                                                                                    
04/13/2018  01:43 PM    <DIR>          ..                                                                                                                                                                                                   
               0 File(s)              0 bytes   
```

If at this point I run the powershell script chef_upgrade.ps1 that still exists in C:\opscode:
```
C:\opscode>powershell                                                                                                                                                                                                                       
Windows PowerShell                                                                                                                                                                                                                          
Copyright (C) 2014 Microsoft Corporation. All rights reserved.                                                                                                                                                                              
                                                                                                                                                                                                                                            
PS C:\opscode> powershell.exe -executionpolicy bypass -file C:\opscode\chef_upgrade.ps1                                                                                                                                                     
                                                                                                                                                                                                                                            
ModuleType Version    Name                                ExportedCommands                                                                                                                                                                  
---------- -------    ----                                ----------------                                                                                                                                                                  
Script     0.0        Omnitruck                           {Get-ProjectMetadata, Install-Project, install}                                                                                                                                   
Installing chef from C:\Users\F-TDSC~1\AppData\Local\Temp\chef-windows-client-x64-13.8.11-x64.msi                                                                                                                                           
SUCCESS: The scheduled task "Chef_upgrade" was successfully deleted.                                                                                                                                                                        
C:/opscode/chef/bin/chef-client : The term 'C:/opscode/chef/bin/chef-client' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that  
the path is correct and try again.                                                                                                                                                                                                          
At C:\opscode\chef_upgrade.ps1:490 char:11                                                                                                                                                                                                  
+           C:/opscode/chef/bin/chef-client                                                                                                                                                                                                 
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                                                 
    + CategoryInfo          : ObjectNotFound: (C:/opscode/chef/bin/chef-client:String) [], CommandNotFoundException                                                                                                                         
    + FullyQualifiedErrorId : CommandNotFoundException
```
Which makes sense because the C:\opscode\chef directory is completely empty.

I don't see it downloading the package (override URL) - but I cleared the Chef cache to see if it may have pulled it earlier.
```C:\opscode>chef-client -o "chef_client_updater::default"
[2018-04-13T14:10:13-07:00] WARN: Ohai::Config[:disabled_plugins] is set. Ohai::Config[:disabled_plugins] is deprecated and will be removed in future releases of ohai. Use ohai.disabled_plugins in your configuration file to configure :d
isabled_plugins for ohai.
Starting Chef Client, version 12.9.41
[2018-04-13T14:10:13-07:00] INFO: *** Chef 12.9.41 ***
[2018-04-13T14:10:13-07:00] INFO: Platform: x64-mingw32
[2018-04-13T14:10:13-07:00] INFO: Chef-client pid: 7036
[2018-04-13T14:10:21-07:00] WARN: Run List override has been provided.
[2018-04-13T14:10:21-07:00] WARN: Original Run List: []
[2018-04-13T14:10:21-07:00] WARN: Overridden Run List: [recipe[chef_client_updater::default]]
[2018-04-13T14:10:21-07:00] INFO: Run List is [recipe[chef_client_updater::default]]
[2018-04-13T14:10:21-07:00] INFO: Run List expands to [chef_client_updater::default]
[2018-04-13T14:10:21-07:00] INFO: Starting Chef Run for W8-HOST
[2018-04-13T14:10:21-07:00] INFO: Running start handlers
[2018-04-13T14:10:21-07:00] INFO: Start handlers complete.
resolving cookbooks for run list: ["chef_client_updater::default"]
[2018-04-13T14:10:21-07:00] INFO: Loading cookbooks [chef_client_updater@3.3.2]
[2018-04-13T14:10:21-07:00] INFO: Skipping removal of obsoleted cookbooks from the cache
Synchronizing Cookbooks:
[2018-04-13T14:10:22-07:00] INFO: Storing updated cookbooks/chef_client_updater/.gitignore in the cache.
[2018-04-13T14:10:22-07:00] INFO: Storing updated cookbooks/chef_client_updater/providers/default.rb in the cache.
[2018-04-13T14:10:22-07:00] INFO: Storing updated cookbooks/chef_client_updater/recipes/default.rb in the cache.
[2018-04-13T14:10:22-07:00] INFO: Storing updated cookbooks/chef_client_updater/attributes/default.rb in the cache.
[2018-04-13T14:10:22-07:00] INFO: Storing updated cookbooks/chef_client_updater/Gemfile in the cache.
[2018-04-13T14:10:22-07:00] INFO: Storing updated cookbooks/chef_client_updater/resources/default.rb in the cache.
[2018-04-13T14:10:22-07:00] INFO: Storing updated cookbooks/chef_client_updater/LICENSE in the cache.
[2018-04-13T14:10:22-07:00] INFO: Storing updated cookbooks/chef_client_updater/libraries/matchers.rb in the cache.
[2018-04-13T14:10:22-07:00] INFO: Storing updated cookbooks/chef_client_updater/CHANGELOG.md in the cache.
[2018-04-13T14:10:22-07:00] INFO: Storing updated cookbooks/chef_client_updater/chefignore in the cache.
[2018-04-13T14:10:22-07:00] INFO: Storing updated cookbooks/chef_client_updater/README.md in the cache.
[2018-04-13T14:10:22-07:00] INFO: Storing updated cookbooks/chef_client_updater/metadata.rb in the cache.
  - chef_client_updater (3.3.2)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 1 resources
Recipe: chef_client_updater::default
  * chef_client_updater[update-chef-client] action update[2018-04-13T14:10:22-07:00] INFO: Processing chef_client_updater[update-chef-client] action update (chef_client_updater::default line 36)

    * powershell_script[name] action run[2018-04-13T14:10:42-07:00] INFO: Processing powershell_script[name] action run (C:/chef/cache/cookbooks/chef_client_updater/providers/default.rb line 296)
SUCCESS: The scheduled task "Chef_upgrade" has successfully been created.
[2018-04-13T14:10:44-07:00] INFO: powershell_script[name] ran successfully

    - execute "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/F-TDSC~1/AppData/Local/Temp/chef-script20180413-7036-1pywk6.ps1"
    - upgrade chef-client 12.9.41 to 13.8.11[2018-04-13T14:10:44-07:00] WARN: post_install_action "exec" not supported for chef-client running forked -- changing to "kill".
[2018-04-13T14:10:44-07:00] WARN: forcing "exec" to "kill" on windows.
[2018-04-13T14:10:44-07:00] WARN: New chef-client installed and exit is allowed. Forcing chef exit!
←[0m
    ================================================================================
    Error executing action `update` on resource 'chef_client_updater[update-chef-client]'
    ================================================================================

    SystemExit
    ----------
    exit

    Resource Declaration:
    ---------------------
    # In C:/chef/cache/cookbooks/chef_client_updater/recipes/default.rb

     36: chef_client_updater 'update-chef-client' do
     37:   version '13.8.11'
     38:   download_url_override 'https://artifact/repo/chef-windows-client-x64/13.8.11/chef-windows-client-x64-13.8.11-x64.msi'
     39:   checksum '25c703511cd3ab38604ca07938ad238b381c4f30d4375f87f67ecd04bcbb4f90'
     40:   post_install_action 'exec'
     41: end

    Compiled Resource:
    ------------------
    # Declared in C:/chef/cache/cookbooks/chef_client_updater/recipes/default.rb:36:in `from_file'

    chef_client_updater("update-chef-client") do
      action [:update]
      updated true
      updated_by_last_action true
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :chef_client_updater
      cookbook_name "chef_client_updater"
      recipe_name "default"
      version "13.8.11"
      download_url_override "https://artifact/repo/chef-windows-client-x64/13.8.11/chef-windows-client-x64-13.8.11-x64.msi"
      checksum "25c703511cd3ab38604ca07938ad238b381c4f30d4375f87f67ecd04bcbb4f90"
      post_install_action "kill"
      product_name "chef"
      exec_command "C:/opscode/chef/bin/chef-client"
    end

    Platform:
    ---------
    x64-mingw32

[2018-04-13T14:10:44-07:00] INFO: Running queued delayed notifications before re-raising exception
←[0m
Running handlers:
[2018-04-13T14:10:44-07:00] ERROR: Running exception handlers
Running handlers complete
[2018-04-13T14:10:44-07:00] ERROR: Exception handlers complete
Chef Client failed. 1 resources updated in 30 seconds
[2018-04-13T14:10:44-07:00] INFO: Sending resource update report (run-id: 7e90f5ab-eb32-4fab-b37d-a7c2937f6278)
[2018-04-13T14:10:44-07:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
[2018-04-13T14:10:44-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
The batch file cannot be found.
```

**Comment by algaut** [comment]
Hello there,

I tried to have a look as of why the powershell script would exit like that. In my environments, on 2012R2 VMs, the scheduled task run was only lasting two seconds. I think the problem comes from the push-jobs stop, which takes a bit of time, and the test that is done directly after, checking for any ruby process. Here's what I got while doing this manually on powershell:

`
PS C:\Users\Administrator> Get-Service push-jobs-client -ErrorAction SilentlyContinue | stop-service
PS C:\Users\Administrator> if ((Get-WmiObject Win32_Process -Filter "name = 'ruby.exe'" | Select-Object CommandLine | se
lect-string 'opscode').count -gt 0) {
>>   Write-Output "Chef cannot be upgraded while in use. Exiting..."
>> }
>>
Chef cannot be upgraded while in use. Exiting...
PS C:\Users\Administrator>
`
As you can see, the output is written. In the powershell code, there is also an exit 3 afterwards.

The task is never run again, leaving my VM in a broken state such as yours.

So the two fixes I can think of now are:
- Add a delay between push-jobs shut down and the next test
- Ensure that the task is run again after the exit 3 is sent

Thanks

-

**Comment by Brantone** [comment]
I see that initial post has Chef-client version at 12.9.41, but wonder if it's something in the 13.x part? No issues were experienced with 13.8.5 ; however, now with recently released 13.9.1 experiencing same issues as commented here for 13.8.11 ... so have to wonder: 
Did whatever caused this in 13.8.11 also get into 13.9.1??

Seeing as how 14.1.1 release notes mentions `windows_task` betting completely re-written, should recommendation be just to upgrade to 14.x?

**Comment by wamoore** [comment]
I'm getting the same error when upgrading from 14.0.202 to 14.1.1.  The upgrade basically exist after moving the old client binaries but never actually upgrades to the new client.  It is leaving all the windows boxes with no chef client installed and not checking in.  Add/Remove programs still shows the old version installed.

**Comment by deevidh** [comment]
We're still feeling a lot of pain on this issue.

Surely we can make the upgrade process substantially more reliable by looping over the check for running opscode ruby processes in chef_upgrade.ps1:
```          if ((Get-WmiObject Win32_Process -Filter "name = 'ruby.exe'" | Select-Object CommandLine | select-string 'opscode').count -gt 0) {
            Write-Output "Chef cannot be upgraded while in use. Exiting..."
            exit 8
          }```
Or simply by scheduling the task to run more than once.

Do you want me to submit a PR?

**Comment by RobbertJanSW** [comment]
IDK why the rerun has been removed. The initial scheduled task for this upgrade mechanism was scheduled to run every minute (unless already running). Thats why the scripts "just" bails out like that. It presumes it will retry within a minute.

**Comment by dheerajd-msys** [comment]
With latest cookbook **v3.8.2** client is upgrading properly although with not proper clean up on Windows 2008R2 and upgrading from 12.9.41 to latest.

Also since support for Windows 2008 is removed and unsupported chef client version **v12.9.41** closing this issue for now.

Please feel free to file another issue if get similar issue. 

Thanks!
