### ISSUE TITLE
Fail to upgrade due to missing /sbin in path when running dpkg/install script

### ISSUE THREAD

**Issue by tom-thepixel** [chef-cookbooks/chef_client_updater#116]
### Cookbook version
3.3.3 and 3.3.3

### Chef-client version
13.8.5 trying to upgrade to 13.9.1

### Platform Details
Ubuntu server16.04 LTS completely up to date as of today

### Scenario:
chef-client running on usual 15 minute cron script, but failing every time

### Steps to Reproduce:
chef_client_updater 'Install latest Chef 13.x' do
  version '13'
end

### Expected Result:
chef-client should upgrade from 13.8.5 to 13.9.1

### Actual Result:
When running chef-client as root on the command line, it works as expected, however, if running as root via cron it fails every time it's run, leaving a 49MB directory in /tmp/installer.sh.*, actually using up all of the remaining disk space on one server (using nearly 200MB of disk space each hour with 15 minute runs). Please note that this hasn't been a problem running via cron in the past and chef-client has been upgraded without issue before.

Runtime error from chef report:
-------------------8<-------------------
Error updating chef-client. exit code: 1.
STDERR: dpkg: warning: 'ldconfig' not found in PATH or not executable
dpkg: warning: 'start-stop-daemon' not found in PATH or not executable
dpkg: error: 2 expected programs not found in PATH or not executable
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin

STDOUT: ubuntu 16.04 x86_64
Getting information for chef stable 13 for ubuntu...
downloading https://omnitruck.chef.io/stable/chef/metadata?v=13&p=ubuntu&pv=16.04&m=x86_64
  to file /tmp/install.sh.17929/metadata.txt
trying wget...
sha1	9921fef922bcaf885877e46032ef1ec2fcf37faa
sha256	07a399a16e7eac400a7e1bab7502ffeda33470d37618698d0c8822e410316b99
url	https://packages.chef.io/files/stable/chef/13.9.1/ubuntu/16.04/chef_13.9.1-1_amd64.deb
version	13.9.1
downloaded metadata file looks valid...
downloading https://packages.chef.io/files/stable/chef/13.9.1/ubuntu/16.04/chef_13.9.1-1_amd64.deb
  to file /tmp/install.sh.17929/chef_13.9.1-1_amd64.deb
trying wget...
Comparing checksum with sha256sum...
Installing chef 13
installing with dpkg...
Installation failed
Version: 13
------------------->8-------------------

It appears that the issue is that the /sbin path isn't included in the environment (or possibly via the chef-client call in cron) when running the install script via (chef_client_updater/providers/default.rb 332):
upgrade_command = Mixlib::ShellOut.new(install_script)

**Comment by tom-thepixel** [comment]
I can confirm the following workaround:
If you change the chef-client cron entry to add /sbin to the PATH environment variable (here I've taken the entire path from the root user) it then runs correctly:

*/15 * * * PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin" /usr/bin/chef-client

**Comment by lamont-granquist** [comment]
`Mixlib::ShellOut.new(install_script)` should be changed to use `shell_out!` if possible.

**Comment by dheerajd-msys** [comment]
@tom-thepixel We've tried to reproduce the issue on **Ubuntu16.04** with latest cookbook.
Added attribute `node['chef_client_updater']['restart_chef_via_cron'] == true` in `attributes\default.rb` so as to use cron.
It seems it is running and upgrading perfectly fine at our end. 
## Output 
```
azure@dh-ubu-16:~/chef-repo/cookbooks$ sudo chef-client -z -o chef_client_updater
: 
: 
     - install version ~> 3.11 of package mixlib-install
    - move all files under /opt/chef to /opt/chef.upgrade
    - upgrade chef 13.9.1 to 13.9.4[2020-01-09T07:21:57+00:00] WARN: Chef client is running forked with a supervisor. Sending KILL to parent process!
[2020-01-09T07:21:57+00:00] WARN: New chef-client installed and exit is allowed. Forcing chef exit!
[2020-01-09T07:21:57+00:00] WARN: Chef Client was upgraded, scheduling chef-client start via cron in 5 minutes

    * cron[chef_client_updater] action create[2020-01-09T07:21:57+00:00] INFO: Processing cron[chef_client_updater] action create (/home/azure/chef-repo/.chef/local-mode-cache/cache/cookbooks/chef_client_updater/providers/default.rb line 575)
Killed
azure@dh-ubu-16:~/chef-repo/cookbooks$ [2020-01-09T07:21:57+00:00] INFO: cron[chef_client_updater] added crontab entry

      - add crontab entry for cron[chef_client_updater]
[2020-01-09T07:21:57+00:00] INFO: Running queued delayed notifications before re-raising exception
  
  Running handlers:
[2020-01-09T07:21:57+00:00] ERROR: Running exception handlers
  Running handlers complete
[2020-01-09T07:21:57+00:00] ERROR: Exception handlers complete
  Chef Client failed. 2 resources updated in 23 seconds
[2020-01-09T07:21:57+00:00] FATAL: Stacktrace dumped to /home/azure/chef-repo/.chef/local-mode-cache/cache/chef-stacktrace.out
[2020-01-09T07:21:57+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-01-09T07:21:57+00:00] ERROR: exit

azure@dh-ubu-16:~/chef-repo/cookbooks$ chef-client -v
Chef: 13.9.4
azure@dh-ubu-16:~/chef-repo/cookbooks$

```
Closing for now. Please check with latest cookbook and let us know if you face the issue.
Happy to help!

**Comment by rmoriz** [comment]
Issue still exists with cookbook version 3.12.3 (not tagged on GH but latest on supermarket)

Debian 12


```
Running handlers complete
[2024-12-22T01:22:15+00:00] ERROR: Exception handlers complete
Infra Phase failed. 0 resources updated in 12 seconds
[2024-12-22T01:22:15+00:00] FATAL: Stacktrace dumped to /var/cinc/cache/cinc-stacktrace.out
[2024-12-22T01:22:15+00:00] FATAL: ---------------------------------------------------------------------------------------
[2024-12-22T01:22:15+00:00] FATAL: PLEASE PROVIDE THE CONTENTS OF THE stacktrace.out FILE (above) IF YOU FILE A BUG REPORT
[2024-12-22T01:22:15+00:00] FATAL: ---------------------------------------------------------------------------------------
[2024-12-22T01:22:15+00:00] FATAL: RuntimeError: chef_client_updater[install chef client 18.5.0] (base::default line 24) had an error: RuntimeError: Error updating chef-client. exit code: 1.
STDERR: dpkg: warning: 'ldconfig' not found in PATH or not executable
dpkg: warning: 'start-stop-daemon' not found in PATH or not executable
dpkg: error: 2 expected programs not found in PATH or not executable
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin


```


<details><summary>Details</summary>
<p>

```
Generated at 2024-12-22 01:22:15 +0000
RuntimeError: chef_client_updater[install chef client 18.5.0] (base::default line 24) had an error: RuntimeError: Error updating chef-client. exit code: 1.
STDERR: dpkg: warning: 'ldconfig' not found in PATH or not executable
dpkg: warning: 'start-stop-daemon' not found in PATH or not executable
dpkg: error: 2 expected programs not found in PATH or not executable
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin

STDOUT: debian 12 x86_64
Download URL override specified
/tmp/install.sh.3953/cinc_18.5.0-1_amd64.deb not found
downloading http://downloads.cinc.sh/files/stable/cinc/18.5.0/debian/12/cinc_18.5.0-1_amd64.deb
  to file /tmp/install.sh.3953/cinc_18.5.0-1_amd64.deb
trying wget...
Comparing checksum with sha256sum...
Installing chef 18.5.0
installing with dpkg...
Installation failed
Version: 18.5.0

Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.chef.io/support/tickets
More Chef support resources can be found at https://www.chef.io/support

Please include as many details about the problem as possible i.e., how to reproduce
the problem (if possible), type of the Operating System and its version, etc.,
and any other relevant details that might help us with troubleshooting.


/var/cinc/cache/cookbooks/chef_client_updater/providers/default.rb:444:in `execute_install_script'
/var/cinc/cache/cookbooks/chef_client_updater/providers/default.rb:460:in `block (2 levels) in class_from_file'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/mixin/why_run.rb:51:in `add_action'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/provider.rb:293:in `converge_by'
/var/cinc/cache/cookbooks/chef_client_updater/providers/default.rb:454:in `block in class_from_file'
(eval):2:in `block in action_update'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/provider.rb:304:in `instance_eval'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/provider.rb:304:in `compile_and_converge_action'
(eval):2:in `action_update'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/provider.rb:245:in `run_action'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/resource.rb:601:in `block in run_action'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/resource.rb:628:in `with_umask'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/resource.rb:600:in `run_action'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/runner.rb:74:in `run_action'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/runner.rb:108:in `each'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/runner.rb:108:in `run_all_actions'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/runner.rb:132:in `block in converge'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/resource_collection/stepable_iterator.rb:54:in `each_with_index'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/cinc/embedded/lib/ruby/3.1.0/forwardable.rb:238:in `execute_each_resource'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/runner.rb:130:in `converge'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/client.rb:869:in `block in converge'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/client.rb:864:in `catch'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/client.rb:864:in `converge'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/client.rb:888:in `converge_and_save'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/client.rb:298:in `run'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/application.rb:281:in `block in run_chef_client'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/application.rb:264:in `run_chef_client'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/application/base.rb:352:in `run_application'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/application.rb:67:in `run'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-bin-18.2.7/bin/cinc-client:25:in `<top (required)>'
/usr/bin/cinc-client:180:in `load'
/usr/bin/cinc-client:180:in `<main>
```

</p>
</details>
