### ISSUE TITLE
Upgrading chef-client on windows.

### ISSUE THREAD

**Issue by username-is-already-taken2** [chef-cookbooks/chef_client_updater#2]
Thanks for sharing this, I only watch your youtube video this morning and thought I would give it ago.

### Cookbook version
1.0.0

### Chef-client version
12.18.31

### Platform Details
Windows 2012 R2

### Scenario:
Testing upgrading the preinstalled chef-client in my windows box

### Steps to Reproduce:
I have version 12.18.31 of the chef-client already installed and I was looking to test having this upgraded.

### Expected Result:
latest stable for me is 12.19.36 so I was expecting it to upgrade.

### Actual Result:
Firstly I'll be upfront I did comment out 
`  # require_chef_omnibus: '12.13.37'` in my kitchen.yml as it was trying to down grade my chef client and I thought this was part of the problem.

```
-----> Converging <default-win2012r2>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 5.2.0...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <default-win2012r2>
       Starting Chef Client, version 12.18.31
       resolving cookbooks for run list: ["chef_client_updater::default"]
       Synchronizing Cookbooks:
         - compat_resource (12.16.3)
         - chef_client_updater (1.0.0)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       Converging 1 resources
       Recipe: chef_client_updater::default
         * chef_client_updater_updater[update chef-client] action update[2017-03-31T16:00:25+01:00] WARN: New chef-client installed. Forcing chef exit!


           ================================================================================
           Error executing action `update` on resource 'chef_client_updater_updater[update chef-client]'
           ================================================================================

           SystemExit
           ----------
           exit

           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chef_client_updater/recipes/default.rb

            20: chef_client_updater 'update chef-client' do
            21:   channel node['chef_client_updater']['channel']
            22:   version node['chef_client_updater']['version']
            23:   prevent_downgrade node['chef_client_updater']['prevent_downgrade']
            24:   post_install_action node['chef_client_updater']['post_install_action']
            25: end

           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chef_client_updater/recipes/default.rb:20:in `from_file'

           chef_client_updater_updater("update chef-client") do
             action [:update]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :chef_client_updater
             cookbook_name "chef_client_updater"
             recipe_name "default"
             channel "stable"
             version "latest"
             prevent_downgrade true
             post_install_action "kill"
           end

           Platform:
           ---------
           x64-mingw32


       Running handlers:
       [2017-03-31T16:00:26+01:00] ERROR: Running exception handlers
       Running handlers complete
       [2017-03-31T16:00:26+01:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 39 seconds
       [2017-03-31T16:00:26+01:00] FATAL: Stacktrace dumped to C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
       [2017-03-31T16:00:26+01:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       Starting Chef Client, version 12.18.31
       resolving cookbooks for run list: ["chef_client_updater::default"]
       Synchronizing Cookbooks:
         - compat_resource (12.16.3)
         - chef_client_updater (1.0.0)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       Converging 1 resources
       Recipe: chef_client_updater::default
         * chef_client_updater_updater[update chef-client] action update[2017-03-31T16:01:09+01:00] WARN: New chef-client installed. Forcing chef exit!


           ================================================================================
           Error executing action `update` on resource 'chef_client_updater_updater[update chef-client]'
           ================================================================================

           SystemExit
           ----------
           exit

           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chef_client_updater/recipes/default.rb

            20: chef_client_updater 'update chef-client' do
            21:   channel node['chef_client_updater']['channel']
            22:   version node['chef_client_updater']['version']
            23:   prevent_downgrade node['chef_client_updater']['prevent_downgrade']
            24:   post_install_action node['chef_client_updater']['post_install_action']
            25: end

           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chef_client_updater/recipes/default.rb:20:in `from_file'

           chef_client_updater_updater("update chef-client") do
             action [:update]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :chef_client_updater
             cookbook_name "chef_client_updater"
             recipe_name "default"
             channel "stable"
             version "latest"
             prevent_downgrade true
             post_install_action "kill"
           end

           Platform:
           ---------
           x64-mingw32


       Running handlers:
       [2017-03-31T16:01:10+01:00] ERROR: Running exception handlers
       Running handlers complete
       [2017-03-31T16:01:10+01:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 37 seconds
       [2017-03-31T16:01:10+01:00] FATAL: Stacktrace dumped to C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
       [2017-03-31T16:01:10+01:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-win2012r2>.  Please see .kitchen/logs/default-win2012r2.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

C:\chef-repo\cookbooks\chef_client_updater [gb/windows +0 ~1 -0 !]>
```

This is my stack trace

```
Generated at 2017-03-31 16:01:10 +0100
SystemExit: chef_client_updater_updater[update chef-client] (chef_client_updater::default line 20) had an error: SystemExit: exit
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chef_client_updater/resources/updater.rb:132:in `exit'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chef_client_updater/resources/updater.rb:132:in `run_post_install_action'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chef_client_updater/resources/updater.rb:36:in `block (2 levels) in class_from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/mixin/why_run.rb:52:in `add_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/provider.rb:176:in `converge_by'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chef_client_updater/resources/updater.rb:33:in `block in class_from_file'
(eval):2:in `block in action_update'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/provider.rb:361:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/provider.rb:361:in `compile_and_converge_action'
(eval):2:in `action_update'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/provider.rb:145:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/resource.rb:622:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/runner.rb:69:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/runner.rb:97:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/runner.rb:97:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/runner.rb:97:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/runner.rb:96:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/client.rb:670:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/client.rb:665:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/client.rb:665:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/client.rb:704:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/client.rb:284:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/application.rb:277:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/application.rb:253:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/application.rb:236:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/application/client.rb:427:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:68:in `load'
C:/opscode/chef/bin/chef-client:68:in `<main>'

>>>> Caused by SystemExit: exit
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chef_client_updater/resources/updater.rb:132:in `exit'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chef_client_updater/resources/updater.rb:132:in `run_post_install_action'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chef_client_updater/resources/updater.rb:36:in `block (2 levels) in class_from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/mixin/why_run.rb:52:in `add_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/provider.rb:176:in `converge_by'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chef_client_updater/resources/updater.rb:33:in `block in class_from_file'
(eval):2:in `block in action_update'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/provider.rb:361:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/provider.rb:361:in `compile_and_converge_action'
(eval):2:in `action_update'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/provider.rb:145:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/resource.rb:622:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/runner.rb:69:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/runner.rb:97:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/runner.rb:97:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/runner.rb:97:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/runner.rb:96:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/client.rb:670:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/client.rb:665:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/client.rb:665:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/client.rb:704:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/client.rb:284:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/application.rb:277:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/application.rb:253:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/application.rb:236:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/application/client.rb:427:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:68:in `load'
C:/opscode/chef/bin/chef-client:68:in `<main>'
```

I'm not seeing any evidence of it downloading the new client or attempting to install it before force quiting the chef run the first time.

If you need anything else let me know

Thanks

Gary

**Comment by r0xxDaniel** [comment]
Hey we're facing the same problem on a virtual machine (VMWare vSphere) . It's working fine on a physical host running Windows Server 2016.

Best,
Daniel

**Comment by TechDawg270** [comment]
Same issue here

**Comment by bowersna** [comment]
Similar issue for upgrading Chef-Client on Windows. No compile or run time errors but client run hangs waiting for the current run to finish... any ideas? Works flawlessly on my *nix nodes.

```
  * chef_client_updater_updater[Install Latest Approved Version] action update[2017-05-25T18:37:44-04:00] INFO: Processi
ng chef_client_updater_updater[Install Latest Approved Version] action update (pilot_chef_client_updater::default line 1
6)
[2017-05-25T18:37:44-04:00] WARN: Replacing ourselves with the new version of Chef to continue the run.
[2017-05-25T18:37:50-04:00] WARN: Chef client 2904 is running, will wait for it to finish and then run.
```

**Comment by david-in-perth** [comment]
We're seeing the same problem too.
Platform: Windows Server 2012 R2

* Tried with `chef_client_updater.post_install_action` as both `kill` and `exec`.
* Tried with and without `--no-fork` option on `chef-client` call.
* Tried with versions 1.1.1 and 1.0.2 of chef_client_updater.

**Comment by lamont-granquist** [comment]
hopefully cleaned up by #23 via merging in the changes in #18 

if there's still windows issues after those changes are released, please cut a new issue (even if its the same problem).
