### ISSUE TITLE
cron job creation operations fail on Fedora

### ISSUE THREAD

**Issue by tas50** [chef-cookbooks/chef_client_updater#201]
Fedora no longer has a crontab file:

```
      Recipe: test::default
         * chef_client_updater[Install Chef 13.10.0] action update
           * chef_gem[mixlib-install] action install
             - install version ~> 3.11 of package mixlib-install
           - remove /opt/chef.upgrade from previous Chef Infra Client run
           * chef_gem[mixlib-install] action install (up to date)
           * cron[chef_client_updater] action delete

             ================================================================================
             Error executing action `delete` on resource 'cron[chef_client_updater]'
             ================================================================================

             Chef::Exceptions::Cron
             ----------------------
             Error determining state of chef_client_updater, error: No such file or directory - crontab

             Resource Declaration:
             ---------------------
             # In /tmp/kitchen/cache/cookbooks/chef_client_updater/providers/default.rb

             252:   cron 'chef_client_updater' do
             253:     action :delete
             254:   end unless platform_family?('windows')
             255: end
             256:

             Compiled Resource:
             ------------------
             # Declared in /tmp/kitchen/cache/cookbooks/chef_client_updater/providers/default.rb:252:in `cleanup'

             cron("chef_client_updater") do
        action [:delete]
        default_guard_interpreter :default
        minute "*"
        hour "*"
        day "*"
        month "*"
        weekday "*"
        user "root"
        declared_type :cron
        cookbook_name "test"
             end

             System Info:
             ------------
             chef_version=13.10.0
             platform=fedora
             platform_version=32
             ruby=ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux]
             program_name=/opt/chef/bin/chef-solo
             executable=/opt/chef/bin/chef-solo


           ================================================================================
           Error executing action `update` on resource 'chef_client_updater[Install Chef 13.10.0]'
           ================================================================================

           Chef::Exceptions::Cron
           ----------------------
           cron[chef_client_updater] (/tmp/kitchen/cache/cookbooks/chef_client_updater/providers/default.rb line 252) had an error: Chef::Exceptions::Cron: Error determining state of chef_client_updater, error: No such file or directory - crontab

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/test/recipes/default.rb

             1: chef_client_updater "Install Chef #{node['chef_client_updater']['version']}" do
             2:   channel 'stable'
             3:   version node['chef_client_updater']['version']
             4:   post_install_action 'exec'
             5:   install_timeout 599
             6: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/test/recipes/default.rb:1:in `from_file'

           chef_client_updater("Install Chef 13.10.0") do
             action [:update]
             updated true
             updated_by_last_action true
             default_guard_interpreter :default
             declared_type :chef_client_updater
             cookbook_name "test"
             recipe_name "default"
             channel "stable"
             version "13.10.0"
             post_install_action "exec"
             install_timeout 599
             rubygems_url "https://www.rubygems.org"
           end

           System Info:
           ------------
           chef_version=13.10.0
           platform=fedora
           platform_version=32
           ruby=ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux]
           program_name=/opt/chef/bin/chef-solo
           executable=/opt/chef/bin/chef-solo


       Running handlers:
       [2020-05-27T20:41:43+00:00] ERROR: Running exception handlers
       [2020-05-27T20:41:43+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2020-05-27T20:41:43+00:00] ERROR: Exception handlers complete
       [2020-05-27T20:41:43+00:00] ERROR: Exception handlers complete
       Chef Client failed. 1 resources updated in 03 seconds
       [2020-05-27T20:41:43+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2020-05-27T20:41:43+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2020-05-27T20:41:43+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2020-05-27T20:41:43+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2020-05-27T20:41:43+00:00] FATAL: Chef::Exceptions::Cron: chef_client_updater[Install Chef 13.10.0] (test::default line 1) had an error: Chef::Exceptions::Cron: cron[chef_client_updater] (/tmp/kitchen/cache/cookbooks/chef_client_updater/providers/default.rb line 252) had an error: Chef::Exceptions::Cron: Error determining state of chef_client_updater, error: No such file or directory - crontab
       [2020-05-27T20:41:43+00:00] FATAL: Chef::Exceptions::Cron: chef_client_updater[Install Chef 13.10.0] (test::default line 1) had an error: Chef::Exceptions::Cron: cron[chef_client_updater] (/tmp/kitchen/cache/cookbooks/chef_client_updater/providers/default.rb line 252) had an error: Chef::Exceptions::Cron: Error determining state of chef_client_updater, error: No such file or directory - crontab
```

**Comment by Quantum-Sicarius** [comment]
The same issue occurs on Fedora 32.

Fixed by installing:
`dnf install cronie cronie-anacron`

**Comment by Nirbhay1997** [comment]
@tas50   
I was going through the documentation of fedora  [https://docs.fedoraproject.org/en-US/fedora/rawhide/system-administrators-guide/monitoring-and-automation/Automating_System_Tasks/](url)
`Fedora is pre-configured to run important system tasks to keep the system updated`


But its seems  we have to install it manually in the newer versions (as I checked on 32 and 31)
[https://docs.fedoraproject.org/en-US/fedora/rawhide/system-administrators-guide/monitoring-and-automation/Automating_System_Tasks/#sect-Cron-Installing](url)

We can do this the chef_client_updater by adding some code to check os and  install cron(most probally using shellout)
what's your view this ?

**Comment by dheerajd-msys** [comment]
@tas50 Per your comments in the PR here https://github.com/chef-cookbooks/chef_client_updater/pull/215#issuecomment-717358340 it seems we need not to work on this issue and this issue needs to be closed. Please confirm if I understood it correctly.

**Comment by tas50** [comment]
This issue really just points out a larger flaw in how we're accomplishing product updates that needs to be solved in a more holistic fashion. We could just make sure cron is installed, but the real problem is we shouldn't rely on cron in 2020 on Linux platforms.
