### ISSUE TITLE
Upgrading chef-client on windows.

### ISSUE THREAD

**Issue by jrcoleman** [chef-cookbooks/chef_client_updater#25]
Note: This issue seems to be partially resolved by `smurawski/windows` branch [#18](https://github.com/chef-cookbooks/chef_client_updater/pull/18) so I'm not sure if this is the right place for it.
### Cookbook version
1.1.1

### Chef-client version
12.18.31

### Platform Details
Windows 2012 R2 from AWS

### Scenario:
Upgrade from 12.18.31 to 13.1.31

### Steps to Reproduce:
Made a test cookbook that wraps `chef_client_updater::default` and kitchen.yml that install 12.18.31 with `require_chef_omnibus: 12.18.31`.
```
node.default['chef_client_updater']['version'] = '13.1.31'
node.default['chef_client_updater']['post_install_action'] = 'kill'
include_recipe 'chef_client_updater::default'
```

### Expected Result:
Chef 13.1.31 is installed and old process is killed.
```
       Recipe: chef_client_updater::default
         * chef_client_updater[update chef-client] action update
           - upgrading rubygems to 2.6.11 was 2.6.8
           * chef_gem[mixlib-install] action install
             - install version >= 3.2.1 of package mixlib-install
           - moving all files under c:/opscode/chef to c:/opscode/chef.upgrade
           * powershell_script[name] action run
             - execute "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -E
xecutionPolicy Bypass -InputFormat None -File "C:/Users/ADMINI~1/AppData/Local/Temp/chef-script20170609-2540-84jxa5.ps1"

       [2017-06-09T13:42:09+00:00] WARN: New chef-client installed. Forcing chef exit!
```

### Actual Result:
Setting `['chef_client_updater']['post_install_action'] = 'kill'` causes a `Argument Error: Invalid Memory object`  with `The system cannot find the path specified.` this looks similar to issue [#2](https://github.com/chef-cookbooks/chef_client_updater/issues/2)/[#5](https://github.com/chef-cookbooks/chef_client_updater/issues/5), but I'm not sure if it is the same thing.
```
-----> Converging <default-ec2-workstation-windows-2012r2>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 5.6.4...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Installing Chef Omnibus (12.18.31)
       Downloading package from https://packages.chef.io/files/stable/chef/12.18.31/windows/2012r2/chef-client-12.18.31-
1-x64.msi
       Download complete.
       Successfully verified C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-12.18.31-1-x64.msi
       Installing Chef Omnibus package C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-12.18.31-1-x64.msi
       Installation complete
       Transferring files to <default-ec2-workstation-windows-2012r2>
       Starting Chef Client, version 12.18.31
       Creating a new client identity for default-ec2-workstation-windows-2012r2 using the validator key.
       resolving cookbooks for run list: ["updatetest::default"]
       Synchronizing Cookbooks:
         - chef_client_updater (1.1.1)
         - updatetest (0.1.0)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       Converging 1 resources
       Recipe: chef_client_updater::default
         * chef_client_updater[update chef-client] action update
           - upgrading rubygems to 2.6.11 was 2.6.8
           * chef_gem[mixlib-install] action install
             - install version >= 3.2.1 of package mixlib-install
           - moving all files under c:/opscode/chef to c:/opscode/chef.upgrade[2017-06-09T14:07:19+00:00] WARN: Chef cli
ent is defined for forked runs. Sending TERM to parent process!

           ================================================================================
           Error executing action `update` on resource 'chef_client_updater[update chef-client]'
           ================================================================================

           ArgumentError
           -------------
           Invalid Memory object

           Resource Declaration:
           ---------------------
           # In C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/chef_client_updater/recipes/default.rb

            20: chef_client_updater 'update chef-client' do
            21:   channel node['chef_client_updater']['channel']
            22:   version node['chef_client_updater']['version']
            23:   prevent_downgrade node['chef_client_updater']['prevent_downgrade']
            24:   post_install_action node['chef_client_updater']['post_install_action']
            25:   download_url_override node['chef_client_updater']['download_url_override'] if node['chef_client_update
r']['download_url_override']
            26:   checksum node['chef_client_updater']['checksum'] if node['chef_client_updater']['checksum']
            27: end

           Compiled Resource:
           ------------------
           # Declared in C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/chef_client_updater/recipes/defaul
t.rb:20:in `from_file'

           chef_client_updater("update chef-client") do
             action [:update]
             updated true
             updated_by_last_action true
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :chef_client_updater
             cookbook_name "chef_client_updater"
             recipe_name "default"
             channel "stable"
             version "13.1.31"
             prevent_downgrade true
             post_install_action "kill"
           end

           Platform:
           ---------
           x64-mingw32


       Running handlers:
       [2017-06-09T14:07:19+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2017-06-09T14:07:19+00:00] ERROR: Exception handlers complete
       Chef Client failed. 1 resources updated in 49 seconds
       [2017-06-09T14:07:19+00:00] FATAL: Stacktrace dumped to C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/chef-s
tacktrace.out
       [2017-06-09T14:07:19+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug repor
t
       [2017-06-09T14:07:20+00:00] FATAL: ArgumentError: chef_client_updater[update chef-client] (chef_client_updater::d
efault line 20) had an error: ArgumentError: Invalid Memory object
$$$$$$ The system cannot find the path specified.
```
It doesn't look like the new version of chef was installed. Here is the `C:\opscode` folder on the instance.
```
PS C:\opscode> ls


    Directory: C:\opscode


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----          6/9/2017   2:06 PM            chef.upgrade


PS C:\opscode> .\chef.upgrade\bin\chef-client --version
Chef: 12.18.31
PS C:\opscode>
```
Setting `['chef_client_updater']['post_install_action'] = 'exec'` causes a `No such file or directory - C:/opscode/chef/bin/chef-client` error again with `The system cannot find the path specified.`. 
```
-----> Converging <default-ec2-workstation-windows-2012r2>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 5.6.4...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Installing Chef Omnibus (12.18.31)
       Downloading package from https://packages.chef.io/files/stable/chef/12.18.31/windows/2012r2/chef-client-12.18.31-
1-x64.msi
       Download complete.
       Successfully verified C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-12.18.31-1-x64.msi
       Installing Chef Omnibus package C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-12.18.31-1-x64.msi
       Installation complete
       Transferring files to <default-ec2-workstation-windows-2012r2>
       Starting Chef Client, version 12.18.31
       Creating a new client identity for default-ec2-workstation-windows-2012r2 using the validator key.
       resolving cookbooks for run list: ["updatetest::default"]
       Synchronizing Cookbooks:
         - chef_client_updater (1.1.1)
         - updatetest (0.1.0)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       Converging 1 resources
       Recipe: chef_client_updater::default
         * chef_client_updater[update chef-client] action update
           - upgrading rubygems to 2.6.11 was 2.6.8
           * chef_gem[mixlib-install] action install
             - install version >= 3.2.1 of package mixlib-install
           - moving all files under c:/opscode/chef to c:/opscode/chef.upgrade[2017-06-09T14:19:48+00:00] WARN: Replacin
g ourselves with the new version of Chef to continue the run.

           ================================================================================
           Error executing action `update` on resource 'chef_client_updater[update chef-client]'
           ================================================================================

           Errno::ENOENT
           -------------
           No such file or directory - C:/opscode/chef/bin/chef-client

           Resource Declaration:
           ---------------------
           # In C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/chef_client_updater/recipes/default.rb

            20: chef_client_updater 'update chef-client' do
            21:   channel node['chef_client_updater']['channel']
            22:   version node['chef_client_updater']['version']
            23:   prevent_downgrade node['chef_client_updater']['prevent_downgrade']
            24:   post_install_action node['chef_client_updater']['post_install_action']
            25:   download_url_override node['chef_client_updater']['download_url_override'] if node['chef_client_update
r']['download_url_override']
            26:   checksum node['chef_client_updater']['checksum'] if node['chef_client_updater']['checksum']
            27: end

           Compiled Resource:
           ------------------
           # Declared in C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/chef_client_updater/recipes/defaul
t.rb:20:in `from_file'

           chef_client_updater("update chef-client") do
             action [:update]
             updated true
             updated_by_last_action true
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :chef_client_updater
             cookbook_name "chef_client_updater"
             recipe_name "default"
             channel "stable"
             version "13.1.31"
             prevent_downgrade true
             post_install_action "exec"
             exec_command "C:/opscode/chef/bin/chef-client"
             exec_args ["--local-mode", "--config", "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\client.rb", "--
log_level", "auto", "--force-formatter", "--no-color", "--json-attributes", "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\
kitchen\\dna.json", "--chef-zero-port", "8889"]
           end

           Platform:
           ---------
           x64-mingw32


       Running handlers:
       [2017-06-09T14:19:48+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2017-06-09T14:19:48+00:00] ERROR: Exception handlers complete
       Chef Client failed. 1 resources updated in 49 seconds
       [2017-06-09T14:19:48+00:00] FATAL: Stacktrace dumped to C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/chef-s
tacktrace.out
       [2017-06-09T14:19:48+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug repor
t
       [2017-06-09T14:19:48+00:00] FATAL: Errno::ENOENT: chef_client_updater[update chef-client] (chef_client_updater::d
efault line 20) had an error: Errno::ENOENT: No such file or directory - C:/opscode/chef/bin/chef-client
$$$$$$ The system cannot find the path specified.
```
Again Chef 13.1.31 is not installed.
```
PS C:\opscode> ls


    Directory: C:\opscode


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----          6/9/2017   2:27 PM            chef.upgrade


PS C:\opscode> .\chef.upgrade\bin\chef-client --version
Chef: 12.18.31
PS C:\opscode>
```
The `smurawski/windows` branch [#18](https://github.com/chef-cookbooks/chef_client_updater/pull/18) also hangs when `['chef_client_updater']['post_install_action'] = 'exec'` and the old chef process has to be stopped manually.
```
       [2017-06-09T15:01:32+00:00] WARN: Replacing ourselves with the new version of Chef to continue the run.
       [2017-06-09T15:01:37+00:00] WARN: Chef client 2896 is running, will wait for it to finish and then run.
```
Let me know if you need the stacktrace or anything else.
Thank you for the help.
Jonny

**Comment by lamont-granquist** [comment]
"Sending TERM to parent process" is covered in #18, all of the chef.upgrade stuff is covered by stuff merged to master, by steven's patch, or by patches that i have in flight on my desktop.

closing this for now because these are all bugs getting addressed.  it won't be useful to test this on windows until all the in-flight work lands on a released version.
