### ISSUE TITLE
Fails on Chef 13

### ISSUE THREAD

**Issue by thommay** [chef-cookbooks/chef_client_updater#4]
Running chef_client_updater with the chef 13.0 release candidate results in:

<details>

```
================================================================================
    Error executing action `update` on resource 'chef_client_updater_updater[current]'
    ================================================================================

    Chef::Exceptions::ResourceNotFound
    ----------------------------------
    exec was called, but you probably meant to use an execute resource.  If not, please call Kernel#exec explicitly.  The exec block called was "chef-client"

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/chef_client_updater/resources/updater.rb:125:in `run_post_install_action'
    /var/chef/cache/cookbooks/chef_client_updater/resources/updater.rb:36:in `block (2 levels) in class_from_file'
    /var/chef/cache/cookbooks/chef_client_updater/resources/updater.rb:33:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/base/recipes/default.rb

      7: chef_client_updater 'current' do
      8:   channel 'current'
      9: end
     10:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/base/recipes/default.rb:7:in `from_file'

    chef_client_updater_updater("current") do
      action [:update]
      updated true
      updated_by_last_action true
      default_guard_interpreter :default
      declared_type :chef_client_updater
      cookbook_name "base"
      recipe_name "default"
      channel "current"
    end

    System Info:
    ------------
    chef_version=13.0.113
    platform=ubuntu
    platform_version=16.04
    ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
    program_name=chef-client worker: ppid=4349;start=14:33:43;
    executable=/opt/chef/bin/chef-client
```

</details>

**Comment by tas50** [comment]
Fixed in 1.0.2!
