### ISSUE TITLE
chef_client_updater appears to fail with errors when killing chef-client after an upgrade

### ISSUE THREAD

**Issue by mhedgpeth** [chef-cookbooks/chef_client_updater#55]
When the `chef_client_updater` cookbook runs, it looks like an error happened, but an error didn't happen. I suggest there be a "upgrading" exit status for the chef-client so it doesn't report as an alarming event.

```
[2017-07-14T16:39:02-05:00] WARN: New chef-client installed. Forcing chef exit!

      ================================================================================
      Error executing action `update` on resource 'chef_client_updater[update chef-client]'
      ================================================================================

      SystemExit
      ----------
      exit

      Cookbook Trace:
      ---------------
      D:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:157:in `exit'
      D:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:157:in `run_post_install_action'
      D:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:240:in `block (2 levels) in class_from_file'
      D:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:233:in `block in class_from_file'
      D:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
      D:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels
) in converge'
      D:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
      D:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in conver
ge'
      D:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
      D:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
      D:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels
) in converge'
      D:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
      D:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in conver
ge'
      D:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

      Resource Declaration:
      ---------------------
      # In D:/chef/cache/cookbooks/chef_client_updater/recipes/default.rb

       20: chef_client_updater 'update chef-client' do
       21:   channel node['chef_client_updater']['channel']
       22:   version node['chef_client_updater']['version']
       23:   prevent_downgrade node['chef_client_updater']['prevent_downgrade']
       24:   post_install_action node['chef_client_updater']['post_install_action']
       25:   download_url_override node['chef_client_updater']['download_url_override'] if node['chef_client_updater']['
download_url_override']
       26:   checksum node['chef_client_updater']['checksum'] if node['chef_client_updater']['checksum']
       27: end

      Compiled Resource:
      ------------------
      # Declared in D:/chef/cache/cookbooks/chef_client_updater/recipes/default.rb:20:in `from_file'

      chef_client_updater("update chef-client") do
        action [:update]
        updated true
        updated_by_last_action true
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :chef_client_updater
        cookbook_name "chef_client_updater"
        recipe_name "default"
        channel "stable"
        version "12.21.3"
        prevent_downgrade true
        post_install_action "kill"
        download_url_override "https://artifactory.hospitality.ncr.com:443/artifactory/list/platform/chef-client/chef-cl
ient-12.21.3-1-x64.msi"
        checksum "9120c1502772594f705001844f065d9fa487646b0f86df8df3647db941e48c08"
      end

      Platform:
      ---------
      x64-mingw32


    ================================================================================
    Error executing action `upgrade` on resource 'platform_client_up_to_date[client_up_to_date]'
    ================================================================================

    SystemExit
    ----------
    chef_client_updater[update chef-client] (chef_client_updater::default line 20) had an error: SystemExit: exit

    Cookbook Trace:
    ---------------
    D:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:157:in `exit'
    D:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:157:in `run_post_install_action'
    D:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:240:in `block (2 levels) in class_from_file'
    D:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:233:in `block in class_from_file'
    D:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    D:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels)
in converge'
    D:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    D:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge
'
    D:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
    D:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    D:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels)
in converge'
    D:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    D:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge
'
    D:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

    Resource Declaration:
    ---------------------
    # In D:/chef/cache/cookbooks/platform/recipes/chef_client.rb

      7: platform_client_up_to_date 'client_up_to_date'

    Compiled Resource:
    ------------------
    # Declared in D:/chef/cache/cookbooks/platform/recipes/chef_client.rb:7:in `from_file'

    platform_client_up_to_date("client_up_to_date") do
      action [:upgrade]
      updated true
      updated_by_last_action true
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :platform_client_up_to_date
      cookbook_name "platform"
      recipe_name "chef_client"
    end

    Platform:
    ---------
    x64-mingw32


Running handlers:
[2017-07-14T16:39:03-05:00] ERROR: Running exception handlers
Running handlers complete
[2017-07-14T16:39:03-05:00] ERROR: Exception handlers complete
Chef Client failed. 8 resources updated in 04 minutes 47 seconds
[2017-07-14T16:39:03-05:00] FATAL: Stacktrace dumped to D:/chef/cache/chef-stacktrace.out
[2017-07-14T16:39:03-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
```

**Comment by lamont-granquist** [comment]
This is already less noisy in current chef-client versions:

```
       Unpacking chef (13.1.31-1) ...
       Setting up chef (13.1.31-1) ...
       Thank you for installing Chef!
       Transferring files to <kill-ubuntu-1604>
       Starting Chef Client, version 13.1.31
       Creating a new client identity for kill-ubuntu-1604 using the validator key.
       resolving cookbooks for run list: ["test::kill"]
       Synchronizing Cookbooks:
         - test (1.0.0)
         - chef_client_updater (3.0.1)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       Converging 1 resources
       Recipe: test::kill
         * chef_client_updater[Install latest Chef] action update
           * chef_gem[mixlib-install] action install
             - install version >= 3.3.1 of package mixlib-install
           - moving all files under /opt/chef to /opt/chef.upgrade[2017-07-15T02:24:50+00:00] WARN: Chef client is running forked with a supervisor. Sending TERM to parent process!
       [2017-07-15T02:24:50+00:00] WARN: Chef client is running forked with a supervisor. Sending TERM to parent process!
       [2017-07-15T02:24:50+00:00] FATAL: SIGTERM received, stopping
       [2017-07-15T02:24:50+00:00] FATAL: SIGTERM received, stopping
       [2017-07-15T02:24:50+00:00] WARN: New chef-client installed. Forcing chef exit!
       [2017-07-15T02:24:50+00:00] WARN: New chef-client installed. Forcing chef exit!

         Running handlers:
       [2017-07-15T02:24:50+00:00] ERROR: Running exception handlers
       [2017-07-15T02:24:50+00:00] ERROR: Running exception handlers
         Running handlers complete
       [2017-07-15T02:24:50+00:00] ERROR: Exception handlers complete
       [2017-07-15T02:24:50+00:00] ERROR: Exception handlers complete
         Chef Client failed. 1 resources updated in 14 seconds
       [2017-07-15T02:24:50+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-07-15T02:24:50+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-07-15T02:24:50+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-07-15T02:24:50+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-07-15T02:24:50+00:00] ERROR: exit
       [2017-07-15T02:24:50+00:00] ERROR: exit
```

**Comment by lamont-granquist** [comment]
And yet another example of the duplicated logger lines in chef 13 we still need to track down...

**Comment by mhedgpeth** [comment]
@lamont-granquist I didn't think about testing that on Chef Client 13.X. Thanks for the information.

One other question (before I can make sure this is good): what gets reported to automate and exception handlers? Are they told a failure occurred?

**Comment by lamont-granquist** [comment]
I assume based on `ERROR: Running exception handlers` that it gets reported to automate, I have no idea how it shows up in that UI.

**Comment by tas50** [comment]
@mhedgpeth I've updated the cookbook to slightly improve the log output. Now you will see the message that the upgrade has completed before you see the warning that the kill/exec is going to happen. Previously the exec/kill was within the converge and happened before the logging fired. This might make it a bit more apparent what's going on, even in the older chef-client releases.

**Comment by tas50** [comment]
Closing this out since we've released a version that solves it as much as we can on an old chef client. New clients will handle this much better as @lamont-granquist mentioned
