### ISSUE TITLE
Update failure due to mixlib missing options

### ISSUE THREAD

**Issue by ttdgcp** [chef-cookbooks/chef_client_updater#57]
### Cookbook version
3.0.2

### Chef-client version
12.20.3

### Platform Details
Windows Server 2012 R2

### Scenario:
Use chef_client_updater cookbook in wrapper cookbook to upgrade from v12.20.3 to v13

### Steps to Reproduce:
Create wrapper cookbook, include in a production node's default.rb, run chef-client --once

### Expected Result: 
A full chef run, followed by an upgrade of Chef Client completing successfully

### Actual Result:
It appears that it is failing because mixlib is unable to detect the platform details, despite it being configured in the providers on line 76-82. I'm not sure of the root cause. The full chef-client output along with the stacktrace are below.

```
Recipe: ttd-chef_client_updater::default
  * chef_client_updater[Install latest Chef 13.x] action update[2017-08-08T22:39:23+00:00] INFO: Processing chef_client_updater[Install latest Chef 13.x] action update (ttd-chef_client_updater::default line 1)

    - upgrade rubygems 2.6.10 to 2.6.11[2017-08-08T22:40:03+00:00] INFO: mixlib-install gem not found. Installing now

    * chef_gem[mixlib-install] action install[2017-08-08T22:40:03+00:00] INFO: Processing chef_gem[mixlib-install] action install (c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb line 32)
WARN: Unresolved specs during Gem::Specification.reset:
      aws-sigv4 (~> 1.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
[2017-08-08T22:40:49+00:00] INFO: chef_gem[mixlib-install] installed mixlib-install at >= 3.3.1

      - install version >= 3.3.1 of package mixlib-install
[2017-08-08T22:40:49+00:00] WARN: NO c:/opscode/chef.upgrade DIR TO ROLL BACK TO!

    ================================================================================
    Error executing action update on resource 'chef_client_updater[Install latest Chef 13.x]'
    ================================================================================

    Mixlib::Install::Options::InvalidOptions
    ----------------------------------------
    Must provide platform, platform version and architecture when specifying any platform details

    Cookbook Trace:
    ---------------
    c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:89:in new'
    c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:89:in mixlib_install'
    c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:115:in update_necessary?'
    c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:232:in block in class_from_file'

    Resource Declaration:
    ---------------------
    # In c:/chef/cache/cookbooks/ttd-chef_client_updater/recipes/default.rb

      1: chef_client_updater 'Install latest Chef 13.x' do
      2:   version '13'
      3: end

    Compiled Resource:
    ------------------
    # Declared in c:/chef/cache/cookbooks/ttd-chef_client_updater/recipes/default.rb:1:in from_file'

    chef_client_updater("Install latest Chef 13.x") do
      action [:update]
      updated true
      updated_by_last_action true
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :chef_client_updater
      cookbook_name "ttd-chef_client_updater"
      recipe_name "default"
      version "13"
      post_install_action "kill"
      exec_command "C:/opscode/chef/bin/chef-client"
      exec_args ["--once"]
    end

    Platform:
    ---------
    x64-mingw32
```
-----
```
Generated at 2017-08-08 22:40:50 +0000
Mixlib::Install::Options::InvalidOptions: chef_client_updater[Install latest Chef 13.x] (ttd-chef_client_updater::default line 1) had an error: Mixlib::Install::Options::InvalidOptions: Must provide platform, platform version and architecture when specifying any platform details

C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-install-3.3.3/lib/mixlib/install/options.rb:102:in `validate_options!'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-install-3.3.3/lib/mixlib/install/options.rb:91:in `validate!'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-install-3.3.3/lib/mixlib/install/options.rb:81:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-install-3.3.3/lib/mixlib/install.rb:35:in `new'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-install-3.3.3/lib/mixlib/install.rb:35:in `initialize'
c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:89:in `new'
c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:89:in `mixlib_install'
c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:115:in `update_necessary?'
c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:232:in `block in class_from_file'
(eval):2:in `block in action_update'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/provider.rb:361:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/provider.rb:361:in `compile_and_converge_action'
(eval):2:in `action_update'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/provider.rb:145:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/resource.rb:622:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/runner.rb:69:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/runner.rb:97:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/runner.rb:97:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/runner.rb:97:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/runner.rb:96:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/client.rb:715:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/client.rb:710:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/client.rb:710:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/client.rb:749:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/client.rb:286:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/application.rb:277:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/application.rb:253:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/application.rb:236:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/application/client.rb:427:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:68:in `load'
C:/opscode/chef/bin/chef-client:68:in `<main>'

>>>> Caused by Mixlib::Install::Options::InvalidOptions: Must provide platform, platform version and architecture when specifying any platform details

C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-install-3.3.3/lib/mixlib/install/options.rb:102:in `validate_options!'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-install-3.3.3/lib/mixlib/install/options.rb:91:in `validate!'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-install-3.3.3/lib/mixlib/install/options.rb:81:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-install-3.3.3/lib/mixlib/install.rb:35:in `new'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-install-3.3.3/lib/mixlib/install.rb:35:in `initialize'
c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:89:in `new'
c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:89:in `mixlib_install'
c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:115:in `update_necessary?'
c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:232:in `block in class_from_file'
(eval):2:in `block in action_update'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/provider.rb:361:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/provider.rb:361:in `compile_and_converge_action'
(eval):2:in `action_update'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/provider.rb:145:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/resource.rb:622:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/runner.rb:69:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/runner.rb:97:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/runner.rb:97:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/runner.rb:97:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/runner.rb:96:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/client.rb:715:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/client.rb:710:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/client.rb:710:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/client.rb:749:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/client.rb:286:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/application.rb:277:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/application.rb:253:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/application.rb:236:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/application/client.rb:427:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:68:in `load'
C:/opscode/chef/bin/chef-client:68:in `<main>'
```

**Comment by Magictoys** [comment]
i have same error  with windows 2012 r2 server . 
my chef client version = 12.18.31

i test with chef client version 12.20 / 12.10 and 12.13.37 and has a  same error


error: 

[0mMixlib::Install::Options::InvalidOptions[0m
----------------------------------------[0m
Must provide platform, platform version and architecture when specifying any platform details
[0m
[0mCookbook Trace:[0m
---------------[0m
c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:89:in `new'
[0mc:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:89:in `mixlib_install'
[0mc:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:235:in `block (2 levels) in class_from_file'
[0mc:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:233:in `block in class_from_file'[0m

[0mResource Declaration:[0m
---------------------[0m
# In c:/chef/cache/cookbooks/chef_client_updater/recipes/default.rb
[0m
[0m 20: chef_client_updater 'update chef-client' do
[0m 21:   channel node['chef_client_updater']['channel']
[0m 22:   version node['chef_client_updater']['version']
[0m 23:   prevent_downgrade node['chef_client_updater']['prevent_downgrade']
[0m 24:   post_install_action node['chef_client_updater']['post_install_action']
[0m 25:   download_url_override node['chef_client_updater']['download_url_override'] if node['chef_client_updater']['download_url_override']
[0m 26:   checksum node['chef_client_updater']['checksum'] if node['chef_client_updater']['checksum']
[0m 27: end
[0m
[0mCompiled Resource:[0m


thanks for yr help

**Comment by gitdave225** [comment]
Getting the same issue. Running on Server 2008 R2 with chef client 12.16.42.
  * chef_client_updater[Install 13.0.118] action update
    - upgrading rubygems to 2.6.11 was 2.6.8
    * chef_gem[mixlib-install] action install
      - install version >= 3.3.1 of package mixlib-install

    ================================================================================
    Error executing action `update` on resource 'chef_client_updater[Install 13.0.118]'
    ================================================================================

    Mixlib::Install::Options::InvalidOptions
    ----------------------------------------
    Must provide platform, platform version and architecture when specifying any platform details

    Cookbook Trace:
    ---------------
    c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:89:in `new'
    c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:89:in `mixlib_install'
    c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:235:in `block (2 levels) in class_from_file'
    c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:233:in `block in class_from_file'

**Comment by tas50** [comment]
This is actually a bug in mixlib-install. I'm going to release a new chef_client_updater today that requires the latest mixlib-install in order to fix this.

**Comment by tas50** [comment]
3.0.3 is out and that should install a version of the mixlib-install gem that properly works on windows hosts

**Comment by lphillips1** [comment]
Forgive me, if I am not in the correct space to pose this question; I am new to this thread...
What can and/or should I do about this:?
OpenSSL::Cipher::CipherError
----------------------------
bad decrypt

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/inspired/libraries/default.rb:29:in `final'
  /var/chef/cache/cookbooks/inspired/libraries/default.rb:29:in `decrypt'
  /var/chef/cache/cookbooks/inspired/attributes/default.rb:19:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/inspired/libraries/default.rb:

 22:
 23:    decode_cipher = OpenSSL::Cipher::Cipher.new(alg)
 24:    key = OpenSSL::PKCS5.pbkdf2_hmac_sha1(pass,saltString, 2048, decode_cipher.key_len)
 25:    decode_cipher.decrypt
 26:    decode_cipher.key = key
 27:    decode_cipher.iv = iv
 28:    plain = decode_cipher.update(decryptMe)
 29>>   plain << decode_cipher.final
 30:    return plain
 31:  end
 32:
 33:  def encrypt(plaintext, pass)
 34:    alg = "AES-256-CBC"
 35:
 36:    salt = OpenSSL::Random.random_bytes(16)
 37:    saltString = [salt].pack('m')
 38:


Running handlers:
[2018-09-13T09:01:07-06:00] ERROR: Running exception handlers
Running handlers complete
[2018-09-13T09:01:07-06:00] ERROR: Exception handlers complete
[2018-09-13T09:01:07-06:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 24.467147855 seconds
[2018-09-13T09:01:07-06:00] ERROR: bad decrypt
[2018-09-13T09:01:07-06:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
